/** @type {import('tailwindcss').Config} */

// Colors are driven by CSS custom properties (defined in src/index.css) stored as
// space-separated RGB channels, so a single `.dark` block re-themes the whole app
// and Tailwind opacity modifiers (e.g. `bg-ember-start/10`) still work.
const c = (v) => `rgb(var(${v}) / <alpha-value>)`;

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        ink: c("--ink"),
        canvas: c("--canvas"),
        "canvas-inset": c("--canvas-inset"),
        background: c("--background"),
        surface: c("--surface"),
        "surface-bright": c("--surface-bright"),
        "surface-dim": c("--surface-dim"),
        "surface-container-lowest": c("--surface-container-lowest"),
        "surface-container-low": c("--surface-container-low"),
        "surface-container": c("--surface-container"),
        "surface-container-high": c("--surface-container-high"),
        "surface-container-highest": c("--surface-container-highest"),
        "surface-variant": c("--surface-variant"),
        "surface-tint": c("--surface-tint"),
        hairline: c("--hairline"),
        "hairline-strong": c("--hairline-strong"),
        "body-text": c("--body-text"),
        "mute-text": c("--mute-text"),
        "on-surface": c("--on-surface"),
        "on-surface-variant": c("--on-surface-variant"),
        outline: c("--outline"),
        "outline-variant": c("--outline-variant"),
        primary: c("--primary"),
        "on-primary": c("--on-primary"),
        secondary: c("--secondary"),
        "secondary-container": c("--secondary-container"),
        "tertiary-container": c("--tertiary-container"),
        error: c("--error"),
        "on-error": c("--on-error"),
        "error-container": c("--error-container"),
        "on-error-container": c("--on-error-container"),
        "ember-start": c("--ember-start"),
        "ember-end": c("--ember-end"),
        // A muted "success" green that reads on both themes.
        ok: c("--ok"),
        "ok-soft": c("--ok-soft"),
        warn: c("--warn"),
      },
      fontFamily: {
        sans: ["Geist", "system-ui", "-apple-system", "sans-serif"],
        mono: ["Geist Mono", "ui-monospace", "monospace"],
        "display-lg": ["Geist", "system-ui", "sans-serif"],
        "display-md": ["Geist", "system-ui", "sans-serif"],
        "body-lg": ["Geist", "system-ui", "sans-serif"],
        "body-md": ["Geist", "system-ui", "sans-serif"],
        "body-sm": ["Geist", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Geist", "system-ui", "sans-serif"],
        "label-mono": ["Geist Mono", "ui-monospace", "monospace"],
        "code-block": ["Geist Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-1.28px", fontWeight: "600" }],
        "display-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.96px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "-0.28px", fontWeight: "400" }],
        "label-mono": ["12px", { lineHeight: "16px", letterSpacing: "0px", fontWeight: "400" }],
        "code-block": ["13px", { lineHeight: "20px", letterSpacing: "0px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.64px", fontWeight: "600" }],
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "24px",
        "margin-page": "48px",
      },
      maxWidth: {
        container: "800px",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
